// Code generated by MockGen. DO NOT EDIT.
// Source: ticket_service.go
//
// Generated by this command:
//
//	mockgen -source=ticket_service.go -destination=../mocks/ticket_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/MananLed/evalProjectRailway/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketServiceInterface is a mock of TicketServiceInterface interface.
type MockTicketServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTicketServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTicketServiceInterfaceMockRecorder is the mock recorder for MockTicketServiceInterface.
type MockTicketServiceInterfaceMockRecorder struct {
	mock *MockTicketServiceInterface
}

// NewMockTicketServiceInterface creates a new mock instance.
func NewMockTicketServiceInterface(ctrl *gomock.Controller) *MockTicketServiceInterface {
	mock := &MockTicketServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTicketServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketServiceInterface) EXPECT() *MockTicketServiceInterfaceMockRecorder {
	return m.recorder
}

// BookTicket mocks base method.
func (m *MockTicketServiceInterface) BookTicket(ticket model.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookTicket", ticket)
	ret0, _ := ret[0].(error)
	return ret0
}

// BookTicket indicates an expected call of BookTicket.
func (mr *MockTicketServiceInterfaceMockRecorder) BookTicket(ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookTicket", reflect.TypeOf((*MockTicketServiceInterface)(nil).BookTicket), ticket)
}

// CancelTicket mocks base method.
func (m *MockTicketServiceInterface) CancelTicket(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTicket", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTicket indicates an expected call of CancelTicket.
func (mr *MockTicketServiceInterfaceMockRecorder) CancelTicket(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTicket", reflect.TypeOf((*MockTicketServiceInterface)(nil).CancelTicket), id)
}

// GetTicketByID mocks base method.
func (m *MockTicketServiceInterface) GetTicketByID(id uuid.UUID) (*model.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByID", id)
	ret0, _ := ret[0].(*model.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketByID indicates an expected call of GetTicketByID.
func (mr *MockTicketServiceInterfaceMockRecorder) GetTicketByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByID", reflect.TypeOf((*MockTicketServiceInterface)(nil).GetTicketByID), id)
}

// GetTicketsOfPassenger mocks base method.
func (m *MockTicketServiceInterface) GetTicketsOfPassenger(id uuid.UUID) ([]model.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketsOfPassenger", id)
	ret0, _ := ret[0].([]model.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketsOfPassenger indicates an expected call of GetTicketsOfPassenger.
func (mr *MockTicketServiceInterfaceMockRecorder) GetTicketsOfPassenger(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketsOfPassenger", reflect.TypeOf((*MockTicketServiceInterface)(nil).GetTicketsOfPassenger), id)
}
