// Code generated by MockGen. DO NOT EDIT.
// Source: train_service.go
//
// Generated by this command:
//
//	mockgen -source=train_service.go -destination=../mocks/train_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	model "github.com/MananLed/evalProjectRailway/internal/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTrainServiceInterface is a mock of TrainServiceInterface interface.
type MockTrainServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrainServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTrainServiceInterfaceMockRecorder is the mock recorder for MockTrainServiceInterface.
type MockTrainServiceInterfaceMockRecorder struct {
	mock *MockTrainServiceInterface
}

// NewMockTrainServiceInterface creates a new mock instance.
func NewMockTrainServiceInterface(ctrl *gomock.Controller) *MockTrainServiceInterface {
	mock := &MockTrainServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTrainServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainServiceInterface) EXPECT() *MockTrainServiceInterfaceMockRecorder {
	return m.recorder
}

// AddTrain mocks base method.
func (m *MockTrainServiceInterface) AddTrain(train model.Train) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrain", train)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrain indicates an expected call of AddTrain.
func (mr *MockTrainServiceInterfaceMockRecorder) AddTrain(train any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrain", reflect.TypeOf((*MockTrainServiceInterface)(nil).AddTrain), train)
}

// DeleteTrain mocks base method.
func (m *MockTrainServiceInterface) DeleteTrain(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrain", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrain indicates an expected call of DeleteTrain.
func (mr *MockTrainServiceInterfaceMockRecorder) DeleteTrain(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrain", reflect.TypeOf((*MockTrainServiceInterface)(nil).DeleteTrain), id)
}

// GetTrainByID mocks base method.
func (m *MockTrainServiceInterface) GetTrainByID(id uuid.UUID) (*model.Train, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrainByID", id)
	ret0, _ := ret[0].(*model.Train)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrainByID indicates an expected call of GetTrainByID.
func (mr *MockTrainServiceInterfaceMockRecorder) GetTrainByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrainByID", reflect.TypeOf((*MockTrainServiceInterface)(nil).GetTrainByID), id)
}

// GetTrains mocks base method.
func (m *MockTrainServiceInterface) GetTrains(travelDate time.Time, source, destination string) ([]model.Train, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrains", travelDate, source, destination)
	ret0, _ := ret[0].([]model.Train)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrains indicates an expected call of GetTrains.
func (mr *MockTrainServiceInterfaceMockRecorder) GetTrains(travelDate, source, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrains", reflect.TypeOf((*MockTrainServiceInterface)(nil).GetTrains), travelDate, source, destination)
}
